### ISSUE TITLE
Pomodoro Timer

### ISSUE THREAD

**Issue by mridulaecon** [RoamJS/workbench#103]
@roamhacker here's a list of potential feature enhancements with the Pomodoro Timer. 

1. Have a sound even for when the break ends. Currently, the chime is only for when the 25 minutes are up. 
2. Have adjustable times for the Pomodoro. 
3. A way for it to compute the number of Pomodoro cycles I should do if I tell it the number of hours I want to work as well as the minutes per cycle. 
4. Similarly, if I could know the number of hours I would work if I tell it the number of cycles and minutes per cycle. 
5. A deadline randomiser would be nice (Not sure if this should be a separate enhancement). But something that allows me to set a deadline for a task dependencies permitting, which is non-negotiable. 

These are probably far too many for one enhancement. Choose as you like. :)

**Comment by mridulaecon** [comment]
Hey @roamhacker! 

When you create the clocks feature. Consider using the astrolabe as the icon for the clock. It would look cool, I think.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Moved to Timer Extension
