### ISSUE TITLE
insertion point contex 

### ISSUE THREAD

**Issue by TfTHacker** [RoamJS/workbench#108]
Via Bill Petro on Slack

**Comment by TfTHacker** [comment]
> Outstanding new additions to Roam42. If I might ask, in “Deep Jump Navigation” any possibility of adding j/k as /up/down navigation, so it’s more like vi/vim, in addition to the. up/down arrows?

Also, with this new feature and the “space bar” scrolling (love it), is there any way to indicate where the insertion point is? With the “unofficial roam-toolkit” browser extension, this is done with an orange highlight bar. I’m not recommending this, but how would one know where the “cursor” is for insertion, without using the mouse?
<sub>[View in Slack](https://roamresearch.slack.com/archives/C0190JLGDUJ/p1600017428494600)</sub>

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Lack of user interest
