### ISSUE TITLE
Issue with spacebar in new update

### ISSUE THREAD

**Issue by shugenja** [RoamJS/workbench#109]
With apologies for being totally illiterate when it comes to coding, I'm experiencing an issue related to typing habits that I think was occasioned by the new update, specifically the autocomplete feature using the spacebar.

When Roam42 is enabled, shift+space does not produce a space; when disabled, it does. It's made me realize that I often press the spacebar before I've dismounted the shift, as when I begin sentences with "I." 

The problem is surely with my own typing habits, but it'd be nice to have the option to disable this function, as you've done for some of the other functions.   

In any case, thanks for your great work on this! I love Roam42.

**Comment by TfTHacker** [comment]
Thank you for reporting this. I think I have fixed it. I will just test it for a day or two, then push it out to the public. So please try again in a few days. If it's still not working, please reopen this issue.

good catch!! :-)
