### ISSUE TITLE
Enhancement: Highlight blocks based on timestamps through the day

### ISSUE THREAD

**Issue by abhayprasanna** [RoamJS/workbench#121]
When in Daily Note(s), it would be very cool if a block could be highlighted or brought to focus in some way, e.g., in a special area of the screen, based on the timestamp in it.

So let's say I plan to do something at 10:00 and type that into a block, at around 9:45 it would be great if that block was somehow highlighted say for 30 mins (perhaps those settings could be updated).

Almost like a time notification system.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - @abhayprasanna sounds like an interesting enhancement to the Alert extension?

**Comment by abhayprasanna** [comment]
Could be good for that too! I think Kanban agenda came after this and that helped some for this use case as well.
