### ISSUE TITLE
Auto-capitalization

### ISSUE THREAD

**Issue by Beehtrix** [RoamJS/workbench#128]
Toggle on/off switch to auto-capitalize:
- new bullet points/blocks
- first letter of a sentence after a period
This is useful for stream of consciousness writing and still allowing for it to be somewhat legible with proper capitalization.

**Comment by orkhan10** [comment]
I am using Typinator for all capitalizations after full stops. It does not help with the first sentences though. Would be nice to have the option for this in Roam.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Talk to Brandon Toner who has a hacky version of this on his graph
