### ISSUE TITLE
Roam42 settings/control panel

### ISSUE THREAD

**Issue by Beehtrix** [RoamJS/workbench#130]
- right next to the jump to date button on the top right
- there’s a lot of things that one could toggle on and off
- there’s only so much you can do with hovers and help menus and keyboard shortcuts
- theres a whole manual on Roam42 shortcuts that one can access and customize through a settings/control panel 
- being able to access and customize the full features of Roam42 gives it a very powerful -second nature- to operate and make Roam their own even more
- can also include a "Help" button that includes shortcuts and whatever help knowledge base roam42 has to offer
- including a link to the github itself for feature suggestions
- and whenever a new feature is added, just light up the Roam42 button with a color or exclamation mark or star to indicate there’s a new feature that you may want to try
- and one can go, click the feature toggle on/off, and can click "Help" and see the literature for it
- can also include "Refresh" button for those that need to manually refresh and see new features in action (which might not be necessary since Roam42 is reloaded to latest version anyway when Roam is opened each time, but useful if you want to test new features on the fly)

**Comment by TfTHacker** [comment]
Yes I am thinking about how to build this. you are very right that this is needed

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Will be implemented once each extension has their own roam/js/* page and with Marketplace extension
