### ISSUE TITLE
Roam mobile backlinks

### ISSUE THREAD

**Issue by Beehtrix** [RoamJS/workbench#132]
Having the ability to backlink on mobile by either:
- tap and hold a word and have a "[[ ]]" button in the context menu along copy/paste/select all, etc to convert any word into a backlink. if the word is already a concept/backlink, the context menu should say "[[ ]] to *conceptname*"
- tap and hold a worb and have a "[[ ]]" button appear in the bottom bar alongside block indentation, move block up/down, insert image

**Comment by TfTHacker** [comment]
@Beehtrix I passed this on to Viktor as he is doing a lot of work in mobile. Let's see if he resolves this or not. If not, I will come back to it.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Could become its own extension if interest resurfaces
