### ISSUE TITLE
NER 

### ISSUE THREAD

**Issue by abhayprasanna** [RoamJS/workbench#134]
Imagining something like navigating to any page, invoking a shortcut that then pops up a textbox with NER-processed version of that page in Markdown, which you can then hit "accept" to replace the page with the NER'd blocks.

The example in [this tweet](https://twitter.com/hmprt_eth/status/1307425728204505091?s=20) with The Prince is a good one: the text was run through Named Entity Recognition to identify potential words/phrases to tag based on recognizing them as entities such as people, locations, etc. So rather than one having to manually tag the things they think should be relevant, this automatically identifies useful things to tag for you.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Could beome a RoamJS extension if user interest resurfaces
