### ISSUE TITLE
Adjustments to the Daily Pop up

### ISSUE THREAD

**Issue by mridulaecon** [RoamJS/workbench#139]
Is it possible to make it such that the daily pop can be dragged from anywhere?

Currently, I am only able to drag the daily pop up when the title bar of the pop up is visible. However, when I increase the size of the daily pop up, sometimes the title bar goes outside the view of the window (especially, when the window (PWA) is not in full screen mode. It also happens with using Roam directly in Chrome). Resultantly, I am unable to drag the pop up. I currently just re-size and then move it around. However, this doesn’t work all the time. 

Therefore, it would be nice if we could drag and drop the pop up from anywhere.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Not sure if possible with jsPanel
