### ISSUE TITLE
Autocomplete pages to the right sidebar

### ISSUE THREAD

**Issue by mridulaecon** [RoamJS/workbench#141]
Hi @roamhacker. 

Just an idea to add the autocomplete feature to the right side bar. 

Since we use SHIFT+SPACE for autocomplete, could we do something like SHIFT+SPACE+U for opening things in the right side bar? 

Given the nice way one can search with keywords now. Might become easier to do a detail search plus these keys.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Implemented in Roam with CTRL+Enter
