### ISSUE TITLE
Enhancement: Roam Table export

### ISSUE THREAD

**Issue by abhayprasanna** [RoamJS/workbench#145]
Context: https://roamresearch.slack.com/archives/CNC4881EU/p1601095446065500

I made a little google spreadsheet that pours the Roam blocks that make up a Roam table into a more traditional table given number of columns.

I wonder if this is a feature Roam42 could add.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Could be a feature for a Table enhancements extension
