### ISSUE TITLE
CMD+SHIFT+K insert alias with page name

### ISSUE THREAD

**Issue by TfTHacker** [RoamJS/workbench#150]
Via Brandon
an idea:
Alias-assist shortcut: SHIFT-CMD-K
Rather than just CMD-K, SHIFT-CMD-K would add the highlighted text within square brackets inside the destination link.
Eg. highlighting “Test” and pressing SHIFT-CMD-K would create [Test]([[Test]])
Benefit:
often users are creating aliases to not disturb the formatting of the text they are trying to reference (Caps differences, slight differences in wording, etc).
This would expedite that process significantly, preventing a re-type in the brackets.

1 select text "Text"
2 SHIFT+CMD+K
3 text inserted [Test]([[Test]]) by roam42
4 User left with [[Test]] selected so they can edit the destination in the alias (perhaps its a page, perhaps its some other destination)

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Live with [page synonyms](https://roamjs.com/docs/extensions/page-synonyms)
