### ISSUE TITLE
Enhancement: better export

### ISSUE THREAD

**Issue by anthrolisp** [RoamJS/workbench#162]
Is there a way to have roam42 create enhanced page export for markdown, one that removes wiki links, extraneous bullets in front of paragraphs, etc? Thanks!

**Comment by TfTHacker** [comment]
Thanks for the idea. Can you give me some more details about how this would work:
+ How would it look
+ How activated

**Comment by TfTHacker** [comment]
This is now in the test build and will be available to public in a week or two.
Supports:
pure text 
markdown text
html view

stripping out the roam stuff to make it reusable else where

**Comment by anthrolisp** [comment]
Awesome news! Thank you!!!!!!

**Comment by anthrolisp** [comment]
A further idea is an option to be able to export a page as well as all of the pages that it links to.
