### ISSUE TITLE
Request option to prevent appended space char on autocomplete

### ISSUE THREAD

**Issue by eatondpe** [RoamJS/workbench#172]
Current State:  `META+space` autocompletes and appends a space.

The automatically appended space is frequently an issue for me.

- I frequently need to backspace to remove it.
- When I use it to autocomplete a tag at the end of the line, changing that tag appends yet another space.

So far, this hasn't caused any real problems. Just some blocks that have multiple spaces at the end. Or the aforementioned need to backspace when appending `s`, `'s`, or any other variation.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Should already be fixed
