### ISSUE TITLE
Nested page titles create unreadable jump hints

### ISSUE THREAD

**Issue by tylerwince** [RoamJS/workbench#195]
When attempting to use Deep Nav on a page reference with nested pages (such as `[[[[Weekly Planning]]/2020W44]]` the jump hints overlap and become unreadable. 

The hints still work (and are fairly "guessable" since they typically are based on the letters in the word) but if they vary, it is hard to know what the hint is. 

![image](https://user-images.githubusercontent.com/17678033/97721530-c7811f00-1a86-11eb-9ef4-3594f967ace0.png)

Browser: Chrome
OS: macOS 10.15.7
Roam Version: 0.7.4-06236d67
Roam42 Version: Tester's Build

**Comment by JimmyLv** [comment]
Also for `attr` with two colons `::`, it should be clickable:

![image](https://user-images.githubusercontent.com/4997466/97769640-b0662e00-1b67-11eb-8e04-613be96b66b7.png)

```
- E/Vite 支持 Rollup 打包生产代码:: #E #Vue
```

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Is this still an issue?
