### ISSUE TITLE
Raom42 breaks new drag-to-resize sidebar feature

### ISSUE THREAD

**Issue by CFiggers** [RoamJS/workbench#199]
Roam42 seems to prevent Roam's [new drag-to-resize sidebar feature](https://twitter.com/Conaw/status/1322552065659338753?s=20) from working. To diagnose/replicate, I have disabled 100% of other CSS/JS and used an incognito window (which disables extensions). When Roam42 is disabled, the drag-to-resize works correctly. When Roam42 is enabled, the mouse does not turn into the <-> cursor when mousing over the left border of the sidebar, and clicking + dragging does not resize the sidebar.

**Comment by TfTHacker** [comment]
Sorry to hear about this issue. I will contact you on Twitter and we will work through the issue.
