### ISSUE TITLE
Use smart quotes and dashes

### ISSUE THREAD

**Issue by vkazartsev** [RoamJS/workbench#200]
As over here: https://support.apple.com/en-ie/guide/mac-help/mh35735/mac#:~:text=Use%20smart%20quotes%20and%20dashes

**Comment by TfTHacker** [comment]
Hi there, may I ask why you posted this as an issue

**Comment by vkazartsev** [comment]
'cause I'm new here and can mix things up? 😨

**Comment by TfTHacker** [comment]
That's no problem. I just need a little more context. Are you reporting a problem? Are you making a feature recommendation and if so what is the recommendation.

**Comment by TfTHacker** [comment]
Also, this is for Roam42 plugin, not for Roam. If you mean this for the Roam developers, that is a different GitHub Issues database.

https://github.com/Roam-Research/issues/issues

**Comment by vkazartsev** [comment]
That much I do understand :-)

I doubt this would be high on their agenda right now. It is exactly the thing you'd do with a roam/js extension, though.

Hell, I could probably do it myself tape-and-sticks style, but was hoping for something more sleek 😉

**Comment by vkazartsev** [comment]
```javascript
var dash = "-";
var emdash = "—"; // Shift+Option+Hyphen
var space = " ";
 
document.addEventListener("keydown", handleKeydown, false);

function handleKeydown(event) {
	var target = event.target;
  
	if (event.key !== space) {return; }
//	if (!target.classList.contains("emdashify")) {return; }
 
	var offset = target.selectionStart;
 
	if (target.value[offset - 1] === dash &&
        target.value[offset - 2] === dash && 
        target.value[offset - 3] === space) {
		event.preventDefault();
 
		var beforeDash = target.value.slice(0, (offset - 3));
		var afterDash = target.value.slice(offset);
 
		target.value = (beforeDash + space + emdash + space + afterDash);
 
		target.selectionStart = offset+1;
		target.selectionEnd = offset+1;
	}
}
