### ISSUE TITLE
Enhancement request: Hover-over stability and functionality improvement

### ISSUE THREAD

**Issue by Alexspeaks** [RoamJS/workbench#207]
Hi there Roamans / Roamhacker / Roam42'ers

Here's my enhancement request video :) check it out and tell me what you think! :) (bullet list below video!)

https://www.loom.com/share/fd78cb8172794fec8ec102886120f6af

Bullet list of request ideas
- a more reliable hover-over functionality
- fluidly being able to extend a hover-over window's functionality to that of the daily notes window (ctrl+shift+,) via say, having the cursor in a hover-page and pressing "shift+f" for freeze (or unfreeze)
- Being able to shift+scroll up/down when in a hover-page to increase or decrease it's size
   - To be able to zoom into/through a page by scrolling up so much so that a hover-over page automatically becomes the 
      mainpage. 
   - To be able to scroll backwards from the mainpage and have the parent page emerge in the backround as the new mainpage (while the main-page that you're scrolling out of becomes a freezed/flexible hover-over page.)

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Will address if user interest resurfaces
