### ISSUE TITLE
Enhancement Request: Pinning/Sorting of linked references 

### ISSUE THREAD

**Issue by imtiazzhr** [RoamJS/workbench#210]
Roam has transformed the way academics and researchers used to gather data, take notes, refine and finally publish it. Roam is efficient, subtle and intuitive. Here are a few suggestions to solve some of the issues that I come across while taking notes and then revising them for exams. I think many in academia could also relate to these. 

**What is the idea?**
Pinning some of the linked references under a particular page so that every time we visit a page, the linked references are sorted according to the preferences that we set earlier. This could be handy in many ways, for instance, in case of PROJECTS, AREAS or REVISE pages we would always want to see the PROJECT reference to appear on top amongst the others or "Todo"  page should appear on top of the others. One may have to scroll through hundreds of pages in a massive GRAPH to look up the "Todos" page. You see what you want to see. Does it make sense?

![Pin references](https://user-images.githubusercontent.com/64468545/98454621-aea7f600-2177-11eb-9adb-a749dd1f7f84.png)

**What problems can it solve?**

1.  Mostly used or valuable linked reference will not be buried under the tons of references.
2. Todos related to that particular page can be sorted, so someone would never miss any pending task.

**Elaboration:** Images to illustrate the above idea are uploaded to this folder.  https://photos.app.goo.gl/tiTJV1xKyDSmYQQ48

Thank you for your great work and efforts.

**Comment by drshahid** [comment]
Very nicely Explained Imtiaz. Its like making the most recent projects todo list stick while you scroll through. Thank you for explaining in detail as well

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Live with [Sort References](https://roamjs.com/docs/extensions/sort-references) extension
