### ISSUE TITLE
Enhancement Request: Expand/Collapse/drop and drag the Linked References

### ISSUE THREAD

**Issue by imtiazzhr** [RoamJS/workbench#211]
**Idea:**
User can expand and collapse all the linked references as he does the blocks on the main page. He can drop and drag the linked references to the main page.

![Expand linked references 1](https://user-images.githubusercontent.com/64468545/98454751-1ad72980-2179-11eb-8eba-3811f1e5063d.png)

Being able to read all the linked references without toggling between the blocks can help someone read hundreds of pages just on one loaded screen. For instance, if I added #medicine next to tons of blocks or pages that I created over a period of time, I can simply click #medicine and read all those linked references by expanding or collapsing them all. No more to and fro movement. It would make linked references as powerful as the main pages and blocks. Linked references can be nested under the main page by dragging and dropping. (currently, blocks can be dragged and dropped but not a complete linked referenced page. It's kinda merging of likewise pages after one has taken tons of notes related to that particular idea and want to convert them to a permanent page. Would bring an end to the era of copy-paste.

**Problems faced/ why is this important?**

1.  Can't read all the linked references related to one idea without to and fro browsing between the pages
2.  What if someone wants to go through all the liked references pertaining to a particular idea without moving back and forth between the pages?
3. Often researching about a topic leads to accumulation of hundreds of linked references which may stale if not reviewed and linked to the main idea/topic/page.
4. It will minimize the copy and paste functionality (replaced by drop and drag)

More illustrations to explain this concept are uploaded to this folder: https://photos.app.goo.gl/tiTJV1xKyDSmYQQ48

Thank you for your great work and efforts.

**Comment by drshahid** [comment]
Ok dont know the developer got an idea of this use case or not but if implimented it can be so valuable for students were they can get hold of a complete topic without distraction from the stuff which come in between what maters and what doesn't in a  singke study session. If i am seeing all fever tags in a single place it would be so nice without reading pain, sweeling and similar stuff.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Could add to sort references extension if user interest resurfaces
