### ISSUE TITLE
Enhancement Request: Text editor on mobile browser

### ISSUE THREAD

**Issue by imtiazzhr** [RoamJS/workbench#212]
**Idea:**
ability to add [[]] ,  / , pages with one click directly from the text editor while browsing on phone. 

![1 - Text editor - Roam](https://user-images.githubusercontent.com/64468545/98455094-3fcd9b80-217d-11eb-97fe-598a6943a729.png)

**Significance:** A great chunk of users use Roam on phones despite a no dedicated mobile application yet. And it hurts when someone can't take swift notes with Roam on a mobile browser. By adding [[]] , + , on the current editor would take it to a whole new level till the application rolls out. I am sure developers are cognizant of these limitations.

**Problems faced/ why is this important?**
1. Can't add pages or other backslash functions quickly
2. [[]]  or /   is not a convenient key on mobile keyboards
3. Functionality will enhance the efficiency of quick capture and will diminish the need to use many temporary swift notes taking apps.

More illustrations to explain this concept are uploaded to this folder: https://photos.app.goo.gl/tiTJV1xKyDSmYQQ48

Thank you for your great work and efforts.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Duplicate of https://github.com/dvargas92495/roam42/issues/132
