### ISSUE TITLE
Enhancement Request: Web view of linked references

### ISSUE THREAD

**Issue by imtiazzhr** [RoamJS/workbench#213]
**Idea:**
Being able to Web View the referenced links to take out prints or save them as pdf. Your web viewer in Roam42 makes it a lot easier to create pdfs and take out prints but can the functionality be expanded to REFERENCED LINKS too?  One can select a few referenced links and see them all as pdf. 

**Note:** If my earlier enhancement request #211 is considered, it will partially resolve this issue as one would be able to bilaterally drag and drop the linked references (blocks and pages) between the main page and linked references.

![Print out of referenced links](https://user-images.githubusercontent.com/64468545/98455146-d13d0d80-217d-11eb-8f61-2ec9c0f16959.png)

**Problems faced/ why is this important?**
1. Quick web view of any of the selected pages/ blocks on the main page and linked references.
2. One pdf page can accommodate as much linked references as possible. 
3. More data on a single page, save the hassle of going through various half-filled pages. Efficient use of resources.

More illustrations to explain this concept are uploaded to this folder: https://photos.app.goo.gl/tiTJV1xKyDSmYQQ48

I don't know whether these suggestions are technically viable to implement or not but I thought the ideas might resonate with you. Thank you for your great work and efforts.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Will readdress if user interest resurfaces
