### ISSUE TITLE
Enable "Jump to Date" configuration 

### ISSUE THREAD

**Issue by tylerwince** [RoamJS/workbench#221]
Today the "Jump to Date" section only allows for the days of the week to be ordered from Monday to Sunday. It would be great it there was a way to set the calendar to be Sunday to Saturday"

![image](https://user-images.githubusercontent.com/17678033/98996406-0932b080-24f0-11eb-9e9a-0908540b80ea.png)

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Native to Roam
