### ISSUE TITLE
Feature Request: Allow automatic Export All as EDN on a trigger

### ISSUE THREAD

**Issue by eatondpe** [RoamJS/workbench#225]
How possible would it be to perform an `Export All as EDN`? At startup, on a defined schedule, whatever.

Several of us, myself and Mridula, have stopped using the auto-backup to git. It has a high failure rate and we both found that, once again, we went weeks with no successful backup. So we're both just doing manual EDN backups.

I suppose that without a means to trigger the backup to the default download folder, you would have to simulate mouse clicks. But then you would also have to know where the menu is on the screen. That last would be a real challenge.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Native to Roam
