### ISSUE TITLE
Enhancement Request: Enable Web View in PWA/Standalone Electron App

### ISSUE THREAD

**Issue by joshbrake** [RoamJS/workbench#253]
Currently the web preview feature tries to open the webview in a separate window outside of Roam but this feature does not work properly in the PWA on iOS or when running Roam in a standalone electron app on the desktop. Clicking the web preview button in these situation just doesn't do anything.

My desired functionality would be that clicking on the web preview link would open as a separate page in the default browser. On iOS in the PWA, this could either launch the default browser separately or just open a new webview inside the PWA (similar to how Roam handles external links currently in the PWA).

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Is this still a bug?

**Comment by joshbrake** [comment]
Yes, this is still not working in the current versions, including the new official Electron-based Roam app.

**Comment by dvargasfuertes** [comment]
Roam Depot version opens in app
