### ISSUE TITLE
List of Page References

### ISSUE THREAD

**Issue by BrianBarry** [RoamJS/workbench#254]
Provide the capability to list all references shown on a page. This is the same information as is found in the filter list. 

Concept: While creating an entry for a "master subject" - e.g., a project or research topic, permit display of a list of all references already associated with the page for the master subject. 

Perhaps

**roam/Reference Lists**

- reference list for:: page x

The list would appear immediately below. If placed on the sidebar it would make assignment of additional tags easier. Fewer missed opportunities to connect ideas.

**Comment by houshuang** [comment]
It would also be really interesting if it were possible to list all block references on a page. I was thinking of experimenting with Joel Chan on encoding an academic paper where we replace all citations with block refs to other papers, but then you'd still want a "sources" section at the bottom.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Native to Roam

**Comment by BrianBarry** [comment]
The demo video is not legible. Screenshot below:
