### ISSUE TITLE
Idea: Toggle visibility of database-wide #[[]] page links with a keystroke

### ISSUE THREAD

**Issue by brandon-toner** [RoamJS/workbench#260]
Problem:
- Heavily tagged blocks begin to distract from the content of the block, causing unnecessary distraction through visual noise.

Proposed solution:
- Be able to toggle the visibility of pages in the format of #[[]] using a keystroke. (Not affecting the visibility of [[]] pages)

Workarounds or alternatives:
- Use * aliases (Kinda works, but is super time consuming to convert tags to this format, especially annoying if this is a short-term workaround.)
- Deal with it. 

Perhaps this is comparative in structure to [[Privacy Mode]].

Referenced discussion: https://twitter.com/brandontoner/status/1332735485509312513?s=21

Looking forward:
- This functionality, in combination with ways to easily append a tag to multiple blocks, will lead me to be much more liberal with tags — giving me more data points to use in queries (and all the benefits that that can open)

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Native to Roam
