### ISSUE TITLE
Fill out all blocks instantly when using a template

### ISSUE THREAD

**Issue by tntmarket** [RoamJS/workbench#261]
It seems that templates fill out blocks one at a time, and indentation is controlled using `Tab`: https://github.com/roamhacker/roam42/blob/f43b176feab171c3a7b7ca36700db88e69155c94/ext/smartBlocks.js#L203

I think it's possible to fill out all the blocks in the template instantly by:

1. Building the string
2. Copying it to the clipboard
3. Pasting it all into a single block
4. Individual blocks will be created

This would smooth out the UX for larger templates (or templates that call other templates). I currently use Keyboard Maestro, and it's able to fill out templates in one go.

The problem is that line breaks inside blocks are sometimes lost:

* If I copy multiple blocks from Roam, and paste them back into Roam immediately, line breaks in blocks are kept
* If I paste and copy the blocks into another editor (like TextEdit), and back into Roam, then line breaks in blocks are lost
* If I run this in the browser console, line breaks inside blocks are lost:

```javascript
setTimeout(() => {
    navigator.clipboard.writeText([
        '- block 1',
        '- block 2',
        '    - block 3',
        '    - block \nwith linebreak'
    ].join('\n'))
}, 1000)
```

* If if just read and write the clipboard contents through JS, line breaks in blocks are lost

```javascript
setTimeout(async () => {
    const clip = await navigator.clipboard.readText()
    navigator.clipboard.writeText(clip)
}, 1000)
```

I think this has to do with the clipboard content's **MIME Type**, which is possible to control with https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem

I think if we figure out what MIME Type the blocks are when copied from Roam, we'll be able to fill out templates in one go (maybe someone on the Roam team knows?)

**Comment by TfTHacker** [comment]
Thank you for this. It is a good solution to quickly inserting templates. Also Roam has now released a new API and we plan to move toward that in the near future.
