### ISSUE TITLE
Disabling lookupUI breaks typeAheadData script, since roam42.typeAhead is not defined

### ISSUE THREAD

**Issue by akrivka** [RoamJS/workbench#279]
Minor issue. 

The "typeAheadUI.js" script has the "lookupUI" tag, so it gets disabled when roam42.disabledFeatures includes "lookupUI". The following script "typeAheadData.js" still gets included though, and it throws an error since roam42.typeAhead is not defined (otherwise it's defined in typeAheadUI.js").

**Comment by TfTHacker** [comment]
This has been resolved. Please let us know if you still see messages.
