### ISSUE TITLE
roam42.q.blockMentions returns zero results when theere is a comma in the first parameter

### ISSUE THREAD

**Issue by ZainRizvi** [RoamJS/workbench#281]
I expected it to return all block mentions regardless of what I named the page

As an example, running the following code returned zero results, despite the page and references to it existing:

`roam42.q.blockMentions("If you do this, you should succeed") # zero results` 

Changing the page name to remove the comma and searching for the new name worked:

`roam42.q.blockMentions("If you do this you should succeed") # returns results`

**Comment by TfTHacker** [comment]
Yes, this command does not handle a space. Its a weakness in the design that we hope to correct at some point in the future.
