### ISSUE TITLE
feature request for the HTML format converter (Alt-m)

### ISSUE THREAD

**Issue by zsviczian** [RoamJS/workbench#286]
Thanks to my progressive summarization script, my summary was full of references [*](((5nxNZezpy))) ... which were all included as full text in the HTML output. I ended up copying the text to a new page, cleaning all the references, and then running Alt+m. Would be great to have a converter option that strips all [*](((5nxNZezpy))) references.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Will address if user interest resurfaces
