### ISSUE TITLE
Wrap query tools in a div with a class

### ISSUE THREAD

**Issue by houshuang** [RoamJS/workbench#290]
It would be great if the UI controls for the query-tools could just be wrapped in a div with a specific class, so that we could style it differently with CSS - or even conditionally hide it. (I often do queries inside a single page, for all questions for example, and in these cases I want the display as minimal as possible).

Also curious about whether it would be possible to enable sorting by page location (again, if you extract all quotations from a very long document, you might want it sorted by most recently added block, or by where it is in the page)?

**Comment by TfTHacker** [comment]
Did you mean this for Roam or David Vargas? This is not a Roam42 feature as far as I can control.
