### ISSUE TITLE
Deep jump nav hints no longer visible

### ISSUE THREAD

**Issue by tanuj-b** [RoamJS/workbench#298]
Hi,

For most bullet points in main page and right side bar, deep nav hints do not render. They still work though, but not visible during regular usage. Probably some CSS changes that have broken this.

**Comment by TfTHacker** [comment]
Thank you for this report. Yes we have a fix for this in the testers build at Roam42.com. You are welcome to use this. Hopefully in a week we push out an update to the general user base.
