### ISSUE TITLE
Live Preview - Alias link - not working

### ISSUE THREAD

**Issue by pyx900** [RoamJS/workbench#305]
I am unable to get Roam42's LivePreview work for `[aliased-name]([[link]])`.

I see that https://github.com/roamhacker/roam42/pull/131 (which refers to the issue) as closed. Though preview works from All Pages, it appears to be not working for Aliased links.

Is this a bug or by design.
Is there a workaround?

cheers!

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Should be live
