### ISSUE TITLE
Latex compatibility of the converter 

### ISSUE THREAD

**Issue by c3founder** [RoamJS/workbench#326]
When I copy-paste using roam42 converter you remove [[]] and (()), etc. But math remains as a double dollar sign $$\beta$$. But regular latex needs a single $\beta$. So when I copy/paste text from the page to a latex editor I need to manually replace all $$ with $. It'd be nice to have $$->$ as a part of the converter. Thanks!

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Duplicate of https://github.com/dvargas92495/roam42/issues/277
