### ISSUE TITLE
Enhancement request: sidebar expand/collapse

### ISSUE THREAD

**Issue by cobblepot1** [RoamJS/workbench#330]
Add keyboard shortcuts to expand/collapse in sidebar - both expand/collapse all and expand/collapse all child blocks (all levels).

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Native to Roam

**Comment by cobblepot1** [comment]
There is a keyboard shortcut for this native to Roam?

**Comment by dvargasfuertes** [comment]
rereading the issue - is this referring to just blocks or the sidebar windows?

**Comment by cobblepot1** [comment]
Sidebar blocks. I know you are working to get a expand/collapse all keyboard shortcut working for the main window. I am asking if there can be a keyboard shortcut to do the same thing for the blocks in the active sidebar section when the cursor is in the sidebar. I am not talking about opening/closing the sidebar itself.

**Comment by dvargasfuertes** [comment]
ah so the change to address open/closing from jump nav on the main window should address the sidebar as well. should be context agnostic
