### ISSUE TITLE
Enhancement request: format multiple blocks at once

### ISSUE THREAD

**Issue by cobblepot1** [RoamJS/workbench#331]
Just like it says - a way to apply heading formatting to multiple highlighted blocks at once (I usually want to remove all formatting from imported pages and it currently takes a long time to do it manually).

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Could add to Mouseless if user interest resurfaces

**Comment by cobblepot1** [comment]
Still interested!

**Comment by dvargasfuertes** [comment]
should now be doable with roam multi select
