### ISSUE TITLE
Enhancement request: keep page title visible

### ISSUE THREAD

**Issue by cobblepot1** [RoamJS/workbench#333]
Keep page title visible at top when scrolling long pages so you always know what page you are on.

**Comment by TfTHacker** [comment]
This can be handled with CSS. Please contact Abhay, I know I have seen that he has resolved this.

**Comment by jfrome1** [comment]
Thanks, but who is Abhay and how do I contact them?

**Comment by TfTHacker** [comment]
https://twitter.com/abhayprasanna
