### ISSUE TITLE
Enhancement request: fix jump nav sidebar indicators

### ISSUE THREAD

**Issue by cobblepot1** [RoamJS/workbench#334]
Currently, the sidebar jump nav indicators (i.e. `s1`, `s2`) interfere with my ability to click the arrow indicator to collapse/expand blocks. Can you move the Jump Nav indicators for the sidebar 10 pixels to the left?

**Comment by TfTHacker** [comment]
We have made some adjustment to this, and hopefully its better. You can also customize this with CSS if you like to tailor it to your environment. You can find a working example here of changing the color of the numbers, which helps a lot under certain themes.
https://roamresearch.com/#/app/roamhacker/page/KOvMfG-wc
