### ISSUE TITLE
Enhancement request: modify autocomplete to not add space

### ISSUE THREAD

**Issue by cobblepot1** [RoamJS/workbench#335]
When using Shift+Space to autocomplete, the process automatically adds a space after the inserted text. This messes up markdown-syntax links where the brackets are inside parentheses, so every time I use autocomplete within alias links I need to delete the space and correct the cursor position. Unfortunately, 85% of my links are alias links, so this is a problem I face dozens of times a day.

e.g. after `Shift + Space` I get this - `[link text]([[autocomplete inserted text]] )`

**Comment by orkhan10** [comment]
![Screenshot 2021-02-09 at 16 20 11](https://user-images.githubusercontent.com/18570936/107384971-bec2cf00-6af2-11eb-960a-1dfbba269ca2.png)

A temporary fix, if you have Keyboard Maestro.

**Comment by orkhan10** [comment]
A temporary fix, if you have Keyboard Maestro.

![Screenshot 2021-02-09 at 16 24 03](https://user-images.githubusercontent.com/18570936/107385676-65a76b00-6af3-11eb-9c84-3f2f472d7897.png)

**Comment by cobblepot1** [comment]
Thanks, I'm on Win 10 unfortunately.

**Comment by TfTHacker** [comment]
What do you think if I make this a 42Setting and you can configure if the space is added or not. I am also planning to turn this feature of by default, as it seems to cause questions for users. So just requires being turned on after a clean install.

**Comment by cobblepot1** [comment]
A configurable setting would be great!

**Comment by cobblepot1** [comment]
Can delete, autocomplete now part of Roam core.
