### ISSUE TITLE
Enhancement request: When using ((Block References)) in the SmartBlock titles, use content of Block Reference instead of its ID

### ISSUE THREAD

**Issue by wohfab** [RoamJS/workbench#339]
When building SmartBlocks, I would like to organize them on a single page. I structure the page with different headings and topics.

For each SmartBlock, I'd like to have a parent block, which holds the SmartBlock title. This way, I can have the code block as a child and also a preview/example as another child.

![image](https://user-images.githubusercontent.com/4539234/104568990-09b30900-5651-11eb-94ee-e5b23a4142df.png)

As seen in the screenshot above, I use a block reference after `#42SmartBlock` to copy over the title of the parent block.

When using the `jj` SmartBlock feature, it shows the ID of the used block reference.

![image](https://user-images.githubusercontent.com/4539234/104569720-526ac200-5651-11eb-974f-9985527509a6.png)

I think it would be great, if the content of the referenced block is shown instead.

Thanks a lot for your great work!

**Comment by TfTHacker** [comment]
Thank you very much for this suggestion. However this would affect the performance of the trigger menu as it queries the DB real time, and this would require resolving the block refs.

For performance reasons we would need to avoid this. Keep the ideas coming!
