### ISSUE TITLE
Mutation observer.observer

### ISSUE THREAD

**Issue by vikramguptamd** [RoamJS/workbench#340]
Hey guys, 
I am not a developer but love using Roam... 

for the past few days, whenever I use roam, this message appears on top.. 
#object[TypeError TypeError: Argument 1 ('target') to MutationObserver.observe must be an instance of Node]

I am using the latest version of safari on a Mac using the lates MacOS

Also.. the "strikeout todo" works randomly.. sometimes it works and sometimes it doesn't 🤷🏼‍♂️ 

Thank you 🙏🏼 

Vik

**Comment by TfTHacker** [comment]
Hi Vik,
Sorry to hear about the problem. Please update to the newest  version of the strikeout todo and see if that helps. Also feel free to DM me on Twitter to resolve this:
https://gist.github.com/roamhacker/94fd043b195af43e3e6fb715bda7409b
