### ISSUE TITLE
Enhancement Request: Improve Converter Markdown, add Fountain, and remove trailing space

### ISSUE THREAD

**Issue by zachphillips** [RoamJS/workbench#343]
In the Converter (which is great, by the way), currently on Github Markdown (flattened), there are a few issues and one major, cataclysmic, world-changing enhancement (that shouldn’t be too difficult):

1. It’s leaving trailing spaces (2 on most lines, sometimes 3?).
2. Ordered and unordered lists aren’t recognized and rendered properly.
3. Bonus points... Could images be rendered out as images rather than their Roam-referenced Markdown image tags? This way, a copy-paste into another system (what this is for) would carry the image to the new place rather than reference it in Roam’s firebase. 
4. While the </br> behavior for shift-return works very properly for Markdown, for us screenwriters 🙏  could you please offer a Fountain (fountain.io) option that displays almost exactly the same but treats hard returns as intentional and simply displays them in plain text with no </br> tags. If you need help implementing the rest of Fountain (it isn’t much), please do let me know. I’m happy to help. Roam is THIS close to being the best screenwriting software ever created (and they weren’t even planning on it). We just need output.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Will address if user interest resurfaces
