### ISSUE TITLE
Bug - Some of the Deep Nav Keys Not Working

### ISSUE THREAD

**Issue by orkhan10** [RoamJS/workbench#351]
Most of the Deep Nav keys work for me except for:

Roam42 Jump nav:

Blocks:
Expand all - x
Collapse all - l

Align left - 1
Center - 2
Align right - 3
Justify - 4
Add reaction - a

I'm on mac catalina. Does anybody else have this issue?

**Comment by TfTHacker** [comment]
Glad you contacted me. I just tried them and they were working for me. Please DM me on twitter or on the Slack channel #roam42 for us to walk through it together.
