### ISSUE TITLE
adding LivePreviewDelay setting disables LivePreview

### ISSUE THREAD

**Issue by heychad** [RoamJS/workbench#352]
The LivePreview function does not work on a [[42Setting]] page with the following blocks:

- #42Setting LivePreview on
- #42Setting LivePreviewDelay 500
- #42Setting DailyNotePopup on

The feature works after removing the "- #42Setting LivePreviewDelay 500" block and refreshing the browser.

**Comment by TfTHacker** [comment]
Thank you for noting this. We will update the docs.
