### ISSUE TITLE
Enhancement request: converter to MS Word

### ISSUE THREAD

**Issue by kvistgaard** [RoamJS/workbench#353]
So far I haven't found an effective way to convert Roam to MS Word, even when using MD plugins in MS Word, so I'm hoping it. could be another coverer in the set offered by Roam42

**Comment by TfTHacker** [comment]
This is a SmartBlock solution to this:
https://github.com/roamhacker/SmartBlocks/issues/209

I am not sure yet if we would build this in due to 3rd party dependencies. The benefit of the SB is that you opt in.

Also check how this HOWTO video: https://www.youtube.com/watch?v=vE9RwR4iWvg
