### ISSUE TITLE
Shift+Space Has Different Behavior with Roam42 Than Stock Roam

### ISSUE THREAD

**Issue by scottdelap** [RoamJS/workbench#355]
I have projects of the name "P: MyProject Name".  When Roam42 is not installed I can start typing page titles as follows in the search box...

- SHIFT + P
- SHIFT + :
- SHIFT + " "
- SHIFT + M
- y

And the search will work fine.  With Roam42 installed the following keystroke does not behave as expected...

- SHIFT + " "
At this point the first partial search term is picked and is opened.  Any ideas on why this is going on?  Shift + " " doesn't seem to be used by Roam42 itself anywhere.

**Comment by orkhan10** [comment]
That is a native Roam42 functionality. Just release the shift when typing space.

**Comment by TfTHacker** [comment]
This can be disabled in the Roam42 menu, feature is called autocomplete. It autocompletes the selection of the first item in a drop down. If you get use to it, it can make selection fast. However, not all users like this flow.
