### ISSUE TITLE
Javascript change in behavior

### ISSUE THREAD

**Issue by mcolacino57** [RoamJS/workbench#358]
Small javascript program to access ToDoist API was working yesterday but failed today. Smartblock is triggered and does a cursor command but JScript below non operational.

var myToken = '<my_token_is_here>'; 
var url = "https://api.todoist.com/rest/v1/tasks?filter=Today"; 
var bearer = 'Bearer ' + myToken; 
var myTasks = $.ajax({url:url, type:"GET", async:false, headers: { Authorization: bearer }, }).responseText; 
for(task of JSON.parse(myTasks)) await roam42.smartBlocks.activeWorkflow.outputAdditionalBlock( "{{[[TODO]]}} [" + task.content + "](" + task.url + ")" ); 
return '';

**Comment by mcolacino57** [comment]
Seems to be working now; not sure what happened

**Comment by TfTHacker** [comment]
Good news!

**Comment by mcolacino57** [comment]
Not sure exactly what happened..it seemed broken this morning. 

Michael Colacino
917-664-4787
***@***.***
