### ISSUE TITLE
workBench - Inbox command doesn't honour tags as destination blocks

### ISSUE THREAD

**Issue by lukod** [RoamJS/workbench#362]
Hello

When I configure the workBench "inbox" feature to paste the block into a page under a text identified by for example `Text: Inbox:`, and the `Inbox:` block exists in the destination page, all works fine.

But, if I reference a tag as opposed to a block as in `Text: #Inbox` or `Text: #[[The Inbox]]` then it won't work. A message will appear in the 'toaster' saying 'operation aborted, text #Inbox doesn't exist' or something similar. Even though it exists in the destination page.

Maybe there's something more specific to do in the configuration which escaped me?

Thank you

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Is this still an issue?

**Comment by lukod** [comment]
Hello

Thanks for getting back to me on this one. I've just checked and it works fine now.

Thanks again
