### ISSUE TITLE
Webview - No longer limits to the focused Block

### ISSUE THREAD

**Issue by achalaggarwal** [RoamJS/workbench#363]
In the previous implementation for the WebView, the web view would only display the current focused block and it's children, which is the same behavior as the Convertor as well.

This is the case with both the Stable release as well as the testers version.

<img width="3008" alt="image" src="https://user-images.githubusercontent.com/175970/113798954-23309200-9722-11eb-83b7-ae5006aedf06.png">

**Comment by achalaggarwal** [comment]
<img width="3008" alt="image" src="https://user-images.githubusercontent.com/175970/113798986-3ba0ac80-9722-11eb-87b0-fad0ad61d438.png">

**Comment by TfTHacker** [comment]
thanks for reporting this. just fixed it.
