### ISSUE TITLE
Can't get rid of queries in smartblock dropdown list

### ISSUE THREAD

**Issue by CCapra** [RoamJS/workbench#365]
I was trying to create a query that would include #today or #soon, but that would not give me content repeated from the 42SmartBlock page (where I have a couple queries embedded in SmartBlocks).  i.e. = #soon or #today, not 42SmartBlock. 

I couldn't figure out how to do that. But - here's the problem - although I was testing the queries on a totally separate page and didn't save them as SmartBlocks, now some of those attempts I tried are showing up in my jj dropdown.

Here's what I'm seeing: ![image](https://user-images.githubusercontent.com/11077871/114607671-6d55ce00-9c62-11eb-87e8-dbbb8f17d2bb.png)

Here's the 42SmartBlock page: 
![image](https://user-images.githubusercontent.com/11077871/114607737-81013480-9c62-11eb-92b9-42b2669d9638.png)

I can't see any reason why those queries show up in the jj dropdown so I suspect a bug. 

Can you provide any help?

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - It's because the 42SmartBlock tag is in the query. Will be addressed with SmartBlocks V2
