### ISSUE TITLE
Customizable keyboard shortcuts

### ISSUE THREAD

**Issue by macintacos** [RoamJS/workbench#366]
I don't even necessarily want the ability to customize _all_ keyboard shortcuts (although that'd obviously be nice), but what always gets me is that I use roam-toolkit's Vim mode, and use `g g` to go to the top of the document all the time. In Roam42, `g` invokes the Deep Nav functionality. I want to keep the Deep Nav functionality (because I think it's fantastic), but I'd like to change it to be a different shortcut (alt+g doesn't seem to work, despite guides saying that it should work).

In general, the ability to customize keyboard shortcuts would be fantastic.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Will address if user interest resurfaces

can't do this in one sweep. Will have to start with whichever features you'd like configurable first
