### ISSUE TITLE
Feature Request: Hotkeys for Increase / Decrease value or date

### ISSUE THREAD

**Issue by itsjustmath** [RoamJS/workbench#368]
With the new electron app I lost the ability to use [roam-toolkit](https://github.com/roam-unofficial/roam-toolkit)’s hotkeys for adjusting dates when a block has focus. 

![image](https://user-images.githubusercontent.com/635044/117585156-b5cba480-b0c5-11eb-9b68-d87f151be82d.png)

![image](https://user-images.githubusercontent.com/635044/117585160-b9f7c200-b0c5-11eb-8889-fcb8814bee0c.png)

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Duplicate of https://github.com/dvargas92495/roam42/issues/86
