### ISSUE TITLE
Smartblock seems to disregard reference text-structure

### ISSUE THREAD

**Issue by yuleeuz** [RoamJS/workbench#370]
(Ive only just joined this forum, I hope this is adequate)
Recently I'm experiencing a strange bug; calling a smart block that pastes page references and links will not follow the structure I defined it by. 

Ive attached images of the block setup

<img width="400" alt="Screenshot 2021-05-23 at 13 13 03" src="https://user-images.githubusercontent.com/84665351/119258114-9c981d00-bbc8-11eb-8d94-dbe40ec89af0.png">

and the resulting text upon calling it 

<img width="400" alt="Screenshot 2021-05-23 at 13 12 40" src="https://user-images.githubusercontent.com/84665351/119258097-8ee29780-bbc8-11eb-868b-a845d3d48bf6.png">

Appreciate all help and ideas!

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Will be addressed with Smartblocks V2
