### ISSUE TITLE
Smart blocks insert the block id of the block tagged as smart block during expansion

### ISSUE THREAD

**Issue by sebastianpech** [RoamJS/workbench#372]
![image](https://user-images.githubusercontent.com/13043943/124897751-e2753d00-dfde-11eb-8b80-cabefab1220e.png)

Roam Version: 0.8.6-2a157972
Roam42 Version: 2021-06-08-18-34 (current)

**Comment by sebastianpech** [comment]
Ok. So this is caused by the zotero-roam extension. Not sure what the problem is though.

**Comment by alixlahuec** [comment]
@dvargas92495 Hi David! Could this be related to the issue that was reported on Slack (https://roamresearch.slack.com/archives/C0190JLGDUJ/p1621988643082100?thread_ts=1621988643.082100&cid=C0190JLGDUJ) about selectors?

**Comment by dvargasfuertes** [comment]
the issue on slack is an html/css conflict between jump nav and zotero, so I don't think it's causing this issue. In fact, I'd be surprised if zotero-roam is at all related to this issue. This could be a v1 smartblocks bug that shouldn't be the case in V2, but in any case I'm still curious. @sebastianpech do you have time for a call next week to help debug? https://calendly.com/dvargas92495/roamjs

**Comment by sebastianpech** [comment]
@dvargas92495 Cool, thanks. Thursday works for me. I'll prepare a mostly empty graph where I can reproduce the issue that I can also share with you.

**Comment by sebastianpech** [comment]
Btw. tried the smartblocks 2 beta. There the issue is gone.

**Comment by dvargasfuertes** [comment]
great news! cool looking forward to syncing up
