### ISSUE TITLE
Option for Live Preview to only display previews when a modifier key is held down

### ISSUE THREAD

**Issue by NoopDawg** [RoamJS/workbench#373]
Desired behavior:
   - Live Preview is on, but hovering over a link only displays the pop-up page when `Ctrl` is held down. A setting for adjusting the modifier key would be a good option to add as well. 

This makes it so we don't need to toggle Live Preview on and off making it a more practical extension to use

**Comment by jmonman7** [comment]
Created a github account just to add this. I'm almost certain there was a period of time where this was an option.

**Comment by Reid-P-Garcia** [comment]
+1000 for this one.

I love the concept, but it's SUPER distracting to the point of unusability.

I think most people who DON'T have an issue with this may not use the mouse as much as I do.

But think about it, if you want to go click on a page to go to it, the live preview instantly pops up, which then makes it impossible (or at least difficult) to actually click on the page to go to it like normal.

Again, I REALLY love the idea (and was excited to try it out), but will leave it turned off for now.

**Comment by dvargasfuertes** [comment]
Oh thanks for bumping this - now that Workbench is in RoamDepot I should give the issues another audit

Modifier key for live preview is on the top of the list for workbench improvements

**Comment by dvargasfuertes** [comment]
new Setting `LivePreviewModifier` supported in the next version

**Comment by Reid-P-Garcia** [comment]
Beautiful, thanks!
