### ISSUE TITLE
Help Menu Stacks when Daily Note is enabled

### ISSUE THREAD

**Issue by dvargasfuertes** [RoamJS/workbench#38]
This was actually the first issue I wanted to PR, and then I found out why it was happening haha. When the `dailyNote` feature is not ignored, the help menu stacks instead of stay in place or close.

Ignored Features is empty:
![image](https://user-images.githubusercontent.com/7143571/90941950-aabed000-e3e1-11ea-9970-8783412a09dd.png)

Daily Note is ignored:
![image](https://user-images.githubusercontent.com/7143571/90942109-5405c600-e3e2-11ea-9743-6e29c81fdfa4.png)

I think it could make it easier to track issues from slack if we add them as issues as well.

**Comment by TfTHacker** [comment]
David,

Good catches! I have a new roam/js block for install: https://roamresearch.com/#/app/roamhacker/page/UeoxCm8rm

I changed IgnoredFeatures to disabledFeatures.

Also, today @Beauhann reported the daily notes issue, and I just fixed it. will be pushing up a fix here shortly.

Thanks for reporting these issues.
