### ISSUE TITLE
Templates don't preserve headings or alignment

### ISSUE THREAD

**Issue by dvargasfuertes** [RoamJS/workbench#44]
Here's a template with a centered heading:

![image](https://user-images.githubusercontent.com/7143571/91096825-a9cdae80-e62c-11ea-971d-4cf5e36e4786.png)

here's what gets outputted when I do `:test_heading:`

![image](https://user-images.githubusercontent.com/7143571/91096890-c4078c80-e62c-11ea-959f-873d6bfb2208.png)

Creating an issue to track, I'd like to tackle this tomorrow!

**Comment by TfTHacker** [comment]
thanks for reporting this. Viktor is upgrading the engine (complete overhaul). I would hold off on any changes to template engine for now. Though it is very interesting code for learning. Bit deep stuff :-)
