### ISSUE TITLE
[Feature Request] Shortcut to toggle left sidebar

### ISSUE THREAD

**Issue by idr4n** [RoamJS/workbench#47]
Thanks for such an amazing addition to Roam Research.

I know there is a shortcut to toggle the right sidebar. It would be great if we could have one as well for the left sidebar. I find myself toggling that one manually very often.

Thanks in advance,

**Comment by TfTHacker** [comment]
Ivan,

THis is a popular request. It's on the short list :-)

**Comment by TfTHacker** [comment]
This has been added and has been live for a few days in Roam42
