### ISSUE TITLE
Customizing the size of live preview page

### ISSUE THREAD

**Issue by c3founder** [RoamJS/workbench#55]
It would be nice to have an option to set the width and height of the live preview window somewhere in your high-level interface that we put in the [[roam/js]].

**Comment by TfTHacker** [comment]
Ok, so I added this feature, you can define this in the roam/js. It's available in the test version (instructions for test version are in #roam42 channel on roamresearch.slack.com.  This should be rolled out in a few days.

window.roam42LivePreview = {
	width:	'400px',
 height: '600px'
}

**Comment by c3founder** [comment]
That's great!
