### ISSUE TITLE
Roam Navigator integration?

### ISSUE THREAD

**Issue by TfTHacker** [RoamJS/workbench#58]
https://github.com/mgsloan/roam-navigator

Allows for keyboard shortcuts for quick navigation

**Comment by cyrulnik** [comment]
Love Roam Navigator. Could this be implemented in Roam/JS so that it doesn't require a plugin?

**Comment by TfTHacker** [comment]
I got permission from the original author to integrate roam navigator into Roam42. I have it in the test build for testers (if you are not in that, come to #Roam42 channel in slack and we can get you setup.)

Very cool feature. For now its experimental, we will see what the feedback is.
