### ISSUE TITLE
Bill P -Ability to underline text

### ISSUE THREAD

**Issue by TfTHacker** [RoamJS/workbench#64]

**Comment by quickfold** [comment]
The potential problem with this is that Markdown doesn't support underlining, so any exported files won't be Markdown-compliant. What is the use case? If it is to underline headings or some element class, perhaps implement in CSS instead? Is it supposed to be in addition to italics or instead of?

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Could be its own extension once there's user interest
