### ISSUE TITLE
pop-up list of commonly used tags or headers Slack - Luhmann

### ISSUE THREAD

**Issue by TfTHacker** [RoamJS/workbench#66]
Feature request: pop-up list of commonly used tags or headers that I can insert by selecting. This is more useful for me than a static template. Rather than entering a whole page of pre-defined text, each item on the template page for this would appear as a pop-up menu and I could enter one by selecting it and hitting enter.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Lack of user interest
