### ISSUE TITLE
Add a button along with every page name in Unlinked References to remove it from Filtering there itself (reducing UX friction while Unlinking)

### ISSUE THREAD

**Issue by iam-Shashank** [RoamJS/workbench#71]
**feature suggestion**: add a button along with every page name in Unlinked References to remove it via Filtering.  (or could just be a cross/unlink icon button like i have shown in the img attached)

**Reason**: while looking at a long list of unlinked refs, when I see some page which isn't relevant, I want to filter it out there itself, instead i have to remember the page name, scroll back to the top to the Filter button, then shift click on that page name to remove it.

**Usecase**: when there are a lot of unlinked references (say >50) and you want to link them all (except 10-15 maybe). for eg: in my usecase I created a #GAN tag, but some other pages with 'gan' in b/w other words are also coming up in Unlinked refs. (ideally this would have been solved if there was some search/filter operator to only take in the word GAN and not other words with 'gan' occuring in between)
![image](https://user-images.githubusercontent.com/34963991/91873492-b4c0b880-ec96-11ea-9ba1-27b24ebaf7c9.png)

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Possible enhancement to [Sort References](https://roamjs.com/docs/extensions/sort-references) extension
