### ISSUE TITLE
Expand/Collapse to a Certain Level of Indentation

### ISSUE THREAD

**Issue by cyrulnik** [RoamJS/workbench#75]
Would be great to have a keyboard shortcut that could expand or collapse all blocks on the current page to a certain level of indentation. So for example, a keyboard shortcut that collapses everything below the second level of indentation in whatever the currently displayed page (or zoomed-in block) is. 

This would be super helpful if I am four or five levels of indentation down and want to just jump to the next second-level point. 

(I think I've suggested this before - -but also stealing from what Cobblepot posted on Slack -- "@RoamHacker Hi, more feature requests. The next priority feature request for me is global expand/collapse one level at a time - i.e. show all level 1 blocks, show all level 1 + level 2 blocks, etc. If people are outlining and haven't used a program with this ability they may not realize how useful it is. And here's the easy keyboard shortcut - use e and c for expand or collapse one level for each press, so 2 presses for 2 levels, and capital E and C for expand or collapse all levels."

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Will be covered by jump nav shortcuts

**Comment by cobblepot1** [comment]
Just checking that jump nav shortcuts will not only allow branch expand/collapse, but also expand/collapse all branches on the page to show e.g. all level 1 + level 2 blocks?

**Comment by dvargasfuertes** [comment]
yup!
