### ISSUE TITLE
Improved sidebar keyboard navigation

### ISSUE THREAD

**Issue by cobblepot1** [RoamJS/workbench#77]
Jump navigation currently only works in the main panel, and if the cursor is in the side panel, it moves the cursor to the main panel. Better would be if jump navigation worked the same way in both the main and side panels, keeping the cursor where it is before hitting `Alt-J` + jump key, and adding a keyboard shortcut to toggle the cursor location between the main and side panels.

**Comment by dvargasfuertes** [comment]
@cobblepot1 Is this still an issue?
