### ISSUE TITLE
Keyboard Shortcut to Increment/Decrement Date

### ISSUE THREAD

**Issue by cyrulnik** [RoamJS/workbench#86]
This is the one remaining feature from Roam Toolkit that (at least for me) hasn't been satisfied by Roam 42. “If you put the cursor inside the date or a number and then press Ctrl+Alt+Up/Down - the date would be incremented or decremented. They keyboard shortcut is configurable.” (Basically, if you want to kick a task to the next day, you put the cursor in the date field, hit the keyboard shortcut, and it goes...) Based on how Roam 42 works -- you might be able to improve on it and be able to increment the date from anywhere in the block -- rather than having to be inside the actual date itself.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Will be covered by Date extension
