### ISSUE TITLE
Consider using a submodule for roam-navigator

### ISSUE THREAD

**Issue by mgsloan** [RoamJS/workbench#87]
In order to make it easy to merge upstream changes from roam-navigator, I suggest the following way to structure it:

1. Fork roam-navigator to `roamhacker/roam-navigator`.

2. `git submodule add https://github.com/roamhacker/roam-navigator`

3. Then, update the roam-navigator.js file with the patch, commit that, and push to the roamhacker fork.

Then maybe `git remote add upstream https://github.com/mgsloan/roam-navigator`.  Then, when you want to pull in my changes you can just do `git pull --rebase upstream master`, which may require resolving merge conflicts.

**Comment by TfTHacker** [comment]
Mike,
Good idea. One issue I have is that Roam42 required I made some unique mod’s to roam-navigator to make it work in roam42 environment. Probably not something to upstream to you. However, if I do add unique functionality, this I will commit back.

**Comment by mgsloan** [comment]
I understand that!  The point of this approach is that it does allow you to maintain patches atop my repository.  With the current approach, it will be more laborious for you to reapply your patches, as there will be no automated help from git.

**Comment by TfTHacker** [comment]
Is there a way of moving just one file from your repository over, or linking it to my version? I only actually need one file from your code base. But this is a very good approach. thank you for pointing it out.

**Comment by mgsloan** [comment]
I do not know of a good way of referencing a single file from another repo with git.

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Related PR closed
