### ISSUE TITLE
Option to make the numbers stay in deep dive function

### ISSUE THREAD

**Issue by Yadhu19996** [RoamJS/workbench#89]
Right now when using the deep dive feature, the numbers listed on the side disappears after we enter a value. If this was present all the time , would be much easier to navigate.

Challenge is that when entering text if by chance its similar to the number combo, then we would jump to that line. Should find some way to solve this

**Comment by TfTHacker** [comment]
So I think this was resolved, rather quick with the roam/js configuration:

`
// Change the Deep navigation options
// activate-on-no-focus - activate navigation mode when body is focused (default: false)
// REMOVE // in front of setting to change it from default setting
window.roamNavigatorSettings = {
  'activate-on-no-focus': true, 
}
`
It is a little funky to synchronize the usage of this feature and some others. But in general, you can escape to turn it off temporarily and other keyboard shortcuts will work.

Thanks for recommendation, nice addition.
