### ISSUE TITLE
Jump to Parent Block

### ISSUE THREAD

**Issue by cyrulnik** [RoamJS/workbench#90]
A keyboard shortcut that jumps directly to the immediate parent block of the child block that is currently being edited.

**Comment by cyrulnik** [comment]
> A keyboard shortcut that jumps directly to the immediate parent block of the child block that is currently being edited.

I can do this with a local Mac keyboard shortcut that sends the following sequence: cmd-. [pause] cmd-, [pause] cmd-, 

Basically zooms in once and then zooms out twice, to essentially land in the bullet of the immediate parent.

Presumably someone who knows what they are doing could do this in a less ass-backwards way :)

**Comment by TfTHacker** [comment]
Also, the new deep navigation stuff easily allows you to move to any node (On test version, ALT+G to activate)
