### ISSUE TITLE
Test Chinese keyboard

### ISSUE THREAD

**Issue by TfTHacker** [RoamJS/workbench#92]
Dear roamhacker, it is easy to get the Chinese keyboard if you have Windows. Just go to the keyboard setting, add the Chinese keyboard, press the Alt+Shift to switch. Then you can try pressing the Shift to switch between English and Chinese keyboard to test the shortcuts you set.

Nick via slack

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Unclear
